name: 🐛 Bug
description: Use esse modelo para relatar bugs no Falforces
labels: [bug]
body:
  - type: markdown
    attributes:
      value: "# Relatório de Bug"

  - type: textarea
    id: description
    attributes:
      label: Descrição do bug
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Passos para reproduzir
      description: Diga-nos como reproduzir esse bug ou como você o encontrou
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: Mídia, se necessário
      description: Captura de tela, GIF, vídeo, etc.
    validations:
      required: false
