name: 🚀 Sugestão/Ideia
description: Use esse modelo para sugerir novas funcionalidades para o Falforces
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: "# Sugestão/Ideia"

  - type: textarea
    id: description
    attributes:
      label: Descrição da funcionalidade
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Como implementar?
      description: Tem alguma ideia de como implementar essa funcionalidade? Conte-nos!
    validations:
      required: false

  - type: textarea
    id: screenshot
    attributes:
      label: Mídia, se aplicável
      description: Captura de tela, GIF, vídeo, etc.
    validations:
      required: false
